// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_MStgl1-AM2uZqOkTpbo1qpFPMYmHxwo',
    appId: '1:767687124332:web:e6adcaa9fd5525f801ff49',
    messagingSenderId: '767687124332',
    projectId: 'blogapp1-5fb8c',
    authDomain: 'blogapp1-5fb8c.firebaseapp.com',
    storageBucket: 'blogapp1-5fb8c.firebasestorage.app',
    measurementId: 'G-VJ7BYJKWLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvj-Byrpb-xrIy8-iI6-h0cj6D2TzaRU',
    appId: '1:767687124332:android:b2fa9dd5233b199101ff49',
    messagingSenderId: '767687124332',
    projectId: 'blogapp1-5fb8c',
    storageBucket: 'blogapp1-5fb8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_W96h3fBVPKgxt9WML1BJE2s9levo7q8',
    appId: '1:767687124332:ios:29b73bb6baf8fb3901ff49',
    messagingSenderId: '767687124332',
    projectId: 'blogapp1-5fb8c',
    storageBucket: 'blogapp1-5fb8c.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_W96h3fBVPKgxt9WML1BJE2s9levo7q8',
    appId: '1:767687124332:ios:29b73bb6baf8fb3901ff49',
    messagingSenderId: '767687124332',
    projectId: 'blogapp1-5fb8c',
    storageBucket: 'blogapp1-5fb8c.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_MStgl1-AM2uZqOkTpbo1qpFPMYmHxwo',
    appId: '1:767687124332:web:8d10da6f3809e92301ff49',
    messagingSenderId: '767687124332',
    projectId: 'blogapp1-5fb8c',
    authDomain: 'blogapp1-5fb8c.firebaseapp.com',
    storageBucket: 'blogapp1-5fb8c.firebasestorage.app',
    measurementId: 'G-RRCLK1MF9D',
  );
}
